import mongoose from 'mongoose';

const reportSchema = new mongoose.Schema({
  reportType: {
    type: String,
    required: [true, 'Report type is required'],
    enum: ['Patient Analytics', 'Financial Report', 'Appointment Report', 'Custom Report']
  },
  title: {
    type: String,
    required: [true, 'Report title is required'],
    trim: true
  },
  description: {
    type: String,
    trim: true
  },
  filters: {
    type: mongoose.Schema.Types.Mixed,
    default: {}
  },
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Generated by is required']
  },
  status: {
    type: String,
    enum: ['Generating', 'Generated', 'Failed'],
    default: 'Generating'
  },
  filePath: {
    type: String,
    trim: true
  },
  fileSize: {
    type: Number
  },
  downloadCount: {
    type: Number,
    default: 0
  },
  lastDownloadedAt: {
    type: Date
  }
}, {
  timestamps: true
});

// Indexes
reportSchema.index({ generatedBy: 1, createdAt: -1 });
reportSchema.index({ reportType: 1 });
reportSchema.index({ status: 1 });

// Virtual for download URL
reportSchema.virtual('downloadUrl').get(function() {
  return `/api/reports/${this._id}/download`;
});

// Ensure virtual fields are serialized
reportSchema.set('toJSON', { virtuals: true });

const Report = mongoose.model('Report', reportSchema);

export default Report;
